# Generated by Django 5.1 on 2025-07-13 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_campus'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='newuser',
            name='users_newus_univers_033394_idx',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='university',
        ),
    ]
