# Generated by Django 5.0.14 on 2025-06-26 12:06

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_newuser_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, default='mtoto', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, region='TZ'),
        ),
    ]
