# Generated by Django 5.0.14 on 2025-06-26 16:48

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_whatsapp_profile_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='TZ'),
        ),
    ]
