# Generated by Django 5.1 on 2025-07-13 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0003_remove_newuser_users_newus_univers_033394_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='newuser',
            name='users_newus_specifi_72fc50_idx',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='preferred_universities',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='specific_location',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='universities',
        ),
        migrations.AddField(
            model_name='profile',
            name='specific_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='core.location'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['campus'], name='users_profi_campus__94a0b9_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['specific_location'], name='users_profi_specifi_086f35_idx'),
        ),
    ]
