# Generated by Django 5.0.14 on 2025-06-26 21:13

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_newuser_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='TZ', unique=True),
        ),
    ]
