# Generated by Django 5.1 on 2025-07-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_location_unique_together_and_more'),
        ('users', '0004_remove_newuser_users_newus_specifi_72fc50_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='profile',
            name='users_profi_campus__94a0b9_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='users_profi_specifi_086f35_idx',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='last_location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='specific_location',
        ),
        migrations.AddField(
            model_name='profile',
            name='campuses',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='core.campus'),
        ),
        migrations.AddField(
            model_name='profile',
            name='universities',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='core.university'),
        ),
    ]
