# Generated by Django 5.1 on 2025-07-14 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_users_profi_campus__94a0b9_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='universities',
        ),
    ]
