# Generated by Django 5.0.14 on 2025-07-12 13:17

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_name', models.CharField(max_length=50, unique=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('radius_km', models.DecimalField(decimal_places=2, default=5.0, help_text="Radius in kilometers to consider as 'near' this university", max_digits=5, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(50.0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='core_univer_name_ed30d3_idx'), models.Index(fields=['short_name'], name='core_univer_short_n_93ae88_idx'), models.Index(fields=['is_active'], name='core_univer_is_acti_53eddc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.university')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['university', 'name'],
                'indexes': [models.Index(fields=['university'], name='core_locati_univers_7c3477_idx'), models.Index(fields=['name'], name='core_locati_name_65ac84_idx'), models.Index(fields=['is_active'], name='core_locati_is_acti_d10f4b_idx')],
                'unique_together': {('university', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='core.university')),
            ],
            options={
                'ordering': ['university', 'name'],
                'indexes': [models.Index(fields=['university'], name='core_campus_univers_de7e3d_idx'), models.Index(fields=['name'], name='core_campus_name_e2643b_idx'), models.Index(fields=['is_active'], name='core_campus_is_acti_199728_idx')],
                'unique_together': {('name', 'university')},
            },
        ),
    ]
