# Generated by Django 5.1 on 2025-07-14 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='location',
            name='university',
        ),
    ]
