# Generated by Django 5.1 on 2025-07-14 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_location_unique_together_and_more'),
        ('users', '0005_remove_profile_users_profi_campus__94a0b9_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
