# Generated by Django 5.1 on 2025-07-12 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='estates.property'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='estates.propertytype'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['owner'], name='estates_pro_owner_i_1f5b31_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_available'], name='estates_pro_is_avai_f715bc_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type'], name='estates_pro_propert_8fad20_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price'], name='estates_pro_price_faef23_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['slug'], name='estates_pro_slug_b6870e_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['location'], name='estates_pro_locatio_af23db_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_available', 'location'], name='estates_pro_is_avai_1f02c6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('owner', 'title')},
        ),
    ]
