# Generated by Django 5.0.14 on 2025-06-22 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='video_processing_status',
            field=models.CharField(choices=[('no_video', 'No Video'), ('pending', 'Pending Upload'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='no_video', help_text='Current processing status of the video.', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_available',
            field=models.BooleanField(default=False, help_text='Indicates if the property is active and visible to users.'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(help_text='Geographical location of the property.', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price of the property in TZS.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='stream_video_id',
            field=models.CharField(blank=True, help_text='Unique ID from Cloudflare Stream for the uploaded video.', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['owner'], name='estates_pro_owner_i_1f5b31_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_available'], name='estates_pro_is_avai_f715bc_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type'], name='estates_pro_propert_8fad20_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price'], name='estates_pro_price_faef23_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['slug'], name='estates_pro_slug_b6870e_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['video_processing_status'], name='estates_pro_video_p_7582ba_idx'),
        ),
    ]
