# Generated by Django 5.0.14 on 2025-07-03 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='property',
            name='estates_pro_video_p_7582ba_idx',
        ),
        migrations.RemoveField(
            model_name='property',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='property',
            name='stream_video_id',
        ),
        migrations.RemoveField(
            model_name='property',
            name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='property',
            name='video_description',
        ),
        migrations.RemoveField(
            model_name='property',
            name='video_name',
        ),
        migrations.RemoveField(
            model_name='property',
            name='video_processing_status',
        ),
    ]
