# Generated by Django 5.1 on 2025-07-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0003_property_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(default='dar es salaam', help_text='Geographical location of the property.', max_length=100),
        ),
    ]
