# Generated by Django 5.1 on 2025-07-14 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_location'),
        ('estates', '0004_alter_property_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['-is_primary', '-created_at'], 'verbose_name': 'Property Image', 'verbose_name_plural': 'Property Images'},
        ),
        migrations.RemoveField(
            model_name='property',
            name='campus',
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='property_images/'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_images', to='estates.property'),
        ),
        migrations.AddField(
            model_name='property',
            name='campus',
            field=models.ManyToManyField(blank=True, related_name='properties', to='core.campus'),
        ),
    ]
