# Generated by Django 5.2 on 2025-04-16 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='productline',
            name='attribute_values',
            field=models.ManyToManyField(related_name='product_lines', to='marketplace.attributevalue'),
        ),
        migrations.AddField(
            model_name='productline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_lines', to='marketplace.product'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.productline'),
        ),
        migrations.AddIndex(
            model_name='attributevalue',
            index=models.Index(fields=['value'], name='marketplace_value_962af8_idx'),
        ),
        migrations.AddIndex(
            model_name='attributevalue',
            index=models.Index(fields=['slug'], name='marketplace_slug_e1757c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together={('attribute', 'value')},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='marketplace_name_40f55f_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='marketplace_slug_d22abd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='marketplace_name_c7bd47_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='marketplace_slug_d409f0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='marketplace_is_acti_90c2f9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured'], name='marketplace_is_feat_d91af6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'category'], name='marketplace_brand_i_4725e0_idx'),
        ),
        migrations.AddIndex(
            model_name='productline',
            index=models.Index(fields=['sku'], name='marketplace_sku_0842d7_idx'),
        ),
        migrations.AddIndex(
            model_name='productline',
            index=models.Index(fields=['price'], name='marketplace_price_b85dda_idx'),
        ),
        migrations.AddIndex(
            model_name='productline',
            index=models.Index(fields=['is_active'], name='marketplace_is_acti_e3c2ef_idx'),
        ),
    ]
