# Generated by Django 5.0.14 on 2025-06-17 22:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='brand',
            name='marketplace_categor_86cfb1_idx',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='category',
        ),
        migrations.AddField(
            model_name='brand',
            name='categories',
            field=models.ManyToManyField(related_name='brands', to='marketplace.category'),
        ),
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together={('attribute', 'value', 'category')},
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['name'], name='marketplace_name_9ae25c_idx'),
        ),
    ]
