# Generated by Django 5.0.14 on 2025-06-27 13:35

import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_remove_brand_marketplace_categor_86cfb1_idx_and_more'),
        ('shops', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['search_vector'], name='product_search_vector_idx', opclasses=['gin']),
        ),
    ]
