# Generated by Django 5.1 on 2025-07-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_location'),
        ('marketplace', '0003_product_campus'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='marketplace_locatio_56048d_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='marketplace_is_acti_6d9aa1_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
        migrations.RemoveField(
            model_name='product',
            name='campus',
        ),
        migrations.AddField(
            model_name='product',
            name='campus',
            field=models.ManyToManyField(blank=True, related_name='products', to='core.campus'),
        ),
    ]
