# Generated by Django 5.0.14 on 2025-06-28 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_product_search_vector_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_search_vector_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='search_vector',
        ),
    ]
