# Generated by Django 5.0.14 on 2025-06-30 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='services',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='event',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='shopmedia',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='shop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useroffer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['user'], name='shops_shop_user_id_149b18_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['is_active'], name='shops_shop_is_acti_bbb154_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'end_date'], name='shops_subsc_status_15a888_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['shop'], name='shops_subsc_shop_id_22bc34_idx'),
        ),
    ]
