# Generated by Django 5.2 on 2025-04-16 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopmedia',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='shoppromotion',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='shopservice',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='shopsubscription',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='shopsubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.subscriptionplan'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['slug', 'is_active'], name='shops_shop_slug_eecfaa_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['region'], name='shops_shop_region_57aa5f_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['created_at'], name='shops_shop_created_8bca73_idx'),
        ),
        migrations.AddIndex(
            model_name='shopsubscription',
            index=models.Index(fields=['is_active', 'is_trial', 'end_date'], name='shops_shops_is_acti_0d3746_idx'),
        ),
    ]
